version: "3"
services:
  locust-master:
    image: swernst/locusts
    volumes:
      - ./scripts:/scripts
    ports:
      - "8089:8089"
  locust-worker:
    image: swernst/locusts 
    command: "--master-host=locust-master"
    volumes:
      - ./scripts:/scripts

boken:
    image: bokeh/demo.bokeh.org 
    command: /bin/bash -c "apt-get update -y && apt-get install python3-pip -y && pip3 install bokeh && bokeh serve && psython3 plotter.py"
    volumes:
      - ./scripts:/scripts
    ports:
      - "5006:5006"