version: "3"
services:
  locust-master: &app_base
    # image: swernst/locusts
    build: .
    volumes:
      - ./scripts:/scripts
    ports:
      - "8080:8089"

  locust-worker: 
    <<: *app_base
    command: "--master-host=locust-master"
    volumes:
      - ./scripts:/scripts